source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'bigdecimal'
gem 'etc'
gem 'handbrake'
gem 'pg'
gem 'progress_bar'
gem 'rails'
gem 'rake'
gem 'require_all'
gem 'streamio-ffmpeg'
gem 'string-similarity'
gem 'solargraph'
gem 'tzinfo-data'
